feat: Add Single Invoice Web Component
RequestNetwork/web-components pull request #220
Opened 2024-11-24 18:12 UTC by sstefdev

Fixes #151 

### Task Overview
Created a standalone web component to view and pay a single request for the Request Invoicing app. This component enables easier sharing via links and faster loading compared to the Invoice Dashboard.

### Changes
- Single Invoice Web Component:
   - Developed a reusable web component for viewing and paying a single request.

- Server-Side Rendering (SSR):
   - Integrated SSR on the Next.js side to optimize rendering and improve performance.

### Next Steps (TODO):
- Move the Single Invoice Web Component to the shared components folder.
- Replace the existing implementation in the invoice-view component with the shared version.

2025-01-10 10:53 UTC, sstefdev commented on packages/single-invoice/src/lib/single-invoice.svelte
> +      },
Removed

2025-01-10 15:13 UTC, sstefdev commented on packages/single-invoice/src/lib/single-invoice.svelte
> +  <div class="innerDrawer">Loading...</div>
Add a loading skeleton here.

2025-01-10 15:28 UTC, MantisClone reviewed
We did a synchronous review of this. This looks like it's on the right track :+1:

2025-01-13 16:24 UTC, sstefdev commented on packages/single-invoice/src/lib/single-invoice.svelte
> +  }
No need, we are already handling the errors

2025-01-13 16:26 UTC, sstefdev commented on packages/single-invoice/src/lib/react/SingleInvoice.d.ts
> +}
Added

2025-01-14 13:25 UTC, aimensahnoun commented
@coderabbitai review

2025-01-15 11:03 UTC, aimensahnoun requested changes

2025-01-15 11:03 UTC, aimensahnoun commented on packages/single-invoice/src/utils/conversion.ts
> + * Maximum slippage (swap) or conversion evolution (conversion pn)
I think this can also be moved to a common utility in shared between both invoice dashboard and this page.

It is also worth noting that the token list PR made changes to the functionality of this method in invoicing dashboard.

2025-01-15 11:03 UTC, aimensahnoun commented on packages/single-invoice/src/utils/formatAddress.ts
> +export const formatAddress = (
Don't we already have this method in shared utility ?

2025-01-15 11:03 UTC, aimensahnoun commented on packages/single-invoice/src/utils/generateInvoice.d.ts
> +export declare const exportToPDF: (invoice: any, currency: any, logo: string) => Promise<void>;
Same with this, we should already have this in shared utility between Invoice dashboard and payment widget

2025-01-15 13:54 UTC, sstefdev commented on packages/single-invoice/src/lib/single-invoice.svelte
> +  const getOneRequest = async (requestId: string) => {
I was adding this to the new commit, we have the whole utils folder, so we will move that to shared

2025-01-15 19:34 UTC, MantisClone commented on packages/single-invoice/src/utils/index.d.ts
Why does this index.d.ts file exist when it's an exact copy of index.ts?

2025-01-15 20:05 UTC, MantisClone commented
This PR is missing a `single-invoice/README.md`. Please add one :pray:

2025-01-20 11:21 UTC, sstefdev commented on packages/single-invoice/src/utils/index.d.ts
It was generated by svelte in the early stages of development

2025-01-20 11:34 UTC, MantisClone commented on shared/utils/formatAddress.ts
> +  return `${checksumAddress.slice(0, first)}...${checksumAddress.slice(-last)}`;
Fixed by improving the `shared/utils/formatAddress.ts` logic and making invoice-dashboard use it and deleting the `invoice-dashboard/formatAddress.ts`

2025-01-20 17:48 UTC, MantisClone approved these changes

2025-01-20 17:51 UTC, merged